#
name: JRU-PULSE CI/CD Pipeline

# Run the Trigger Event on push to main branch
on:
  push:
    branches: [main]

# Python-api Build Job, First Task to build the python-api image
jobs:
  build-python-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code # Checkout the code from the repo
        uses: actions/checkout@v4 # pre-built GH action tht clones the repo to the VM. get the Dockerfiles on to the build server.

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Set up Docker Build Environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Build and Tag the Python-api Docker Image
      - name: Build and Push Python API Image
        uses: docker/build-push-action@v5
        with:
          context: ./python-api  # Path to the Dockerfile directory
          file: ./python-api/Dockerfile  # Path to the Dockerfile
          push: true # Push the image to Docker Hub

          tags: |
            rlyleearl/jru-pulse-python-api:latest
            rlyleearl/jru-pulse-python-api:${{ github.sha }}
    

