#  RU-PULSE CI/CD Pipeline
name: JRU-PULSE CI/CD Pipeline

# Run the Trigger Event on push to main branch
on:
  push:
    branches: [main]

# Jobs Section
jobs:
  # Job 1: Python-api, First Task to build the python-api image
  build-python-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code # Checkout the code from the repo
        uses: actions/checkout@v4 # pre-built GH action tht clones the repo to the VM. get the Dockerfiles on to the build server.

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker Build Environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Build and Tag the Python-api Docker Image
      - name: Build and Push Python API Image
        uses: docker/build-push-action@v5
        with:
          context: ./python-api  # Path to the Dockerfile directory
          file: ./python-api/Dockerfile  # Path to the Dockerfile
          push: true # Push the image to Docker Hub

          tags: |
            rlyleearl/jru-pulse-python-api:latest
            rlyleearl/jru-pulse-python-api:${{ github.sha }}
    
# Job 2: PHP-web-app
  build-web-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code # Checkout the code from th repo
        uses: actions/checkout@v4

        # Login to my DOcker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker Build Environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3    

      # Build and Tag the PHP-web-app Docker Images
      - name: Build and Push PHP Web App Image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app # Path to the Dockerfile directory
          file: ./web-app/Dockerfile  # Path to the Dockerfile
          push: true # Push to Docker Hub

          tags: |
            rlyleearl/jru-pulse-web-app:latest
            rlyleearl/jru-pulse-web-app:${{ github.sha }}

# Parellel Execution of Jobs
  deploy-verification:
    runs-on: ubuntu-latest

    # Will run after both build jobs are complete
    needs: [build-python-api, build-web-app]
    
    steps:
      - name: Report Deployment Sucess
        run: |
          echo "All JRU-PULSE Docker images have been built and pushed successfully!"
          echo "Build Tag: ${{ github.sha }}"
          echo "Ready for deployment"
